package com.MAVLink.common;/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * java mavlink generator tool. It should not be modified by hand.
 */

// MESSAGE AUTOPILOT_VERSION PACKING
import com.MAVLink.MAVLinkPacket;
import com.MAVLink.Messages.MAVLinkMessage;
import com.MAVLink.Messages.MAVLinkPayload;

/**
* Version and capability of autopilot software
*/
public class msg_autopilot_version extends MAVLinkMessage {

    public static final int MAVLINK_MSG_ID_AUTOPILOT_VERSION = 148;
    public static final int MAVLINK_MSG_LENGTH = 48;
    private static final long serialVersionUID = MAVLINK_MSG_ID_AUTOPILOT_VERSION;


      
    /**
    * Autopilot software version number
    */
    public long autopilot_sw_version;
      
    /**
    * OpticalFlow software version number
    */
    public long opticalflow_sw_version;
      
    /**
    * Sonar software version number
    */
    public long sonar_sw_version;
      
    /**
    * Battery software version number
    */
    public long battery_sw_version;
      
    /**
    * Autopilot hardware version number
    */
    public long autopilot_hw_version;
      
    /**
    * Product id
    */
    public short product_id[] = new short[16];
      
    /**
    * Autopilot uid
    */
    public short autopilot_uid[] = new short[12];
    

    /**
    * Generates the payload for a mavlink message for a message of this type
    * @return
    */
    public MAVLinkPacket pack(){
        MAVLinkPacket packet = new MAVLinkPacket(MAVLINK_MSG_LENGTH);
        packet.sysid = 255;
        packet.compid = 190;
        packet.msgid = MAVLINK_MSG_ID_AUTOPILOT_VERSION;
              
        packet.payload.putUnsignedInt(autopilot_sw_version);
              
        packet.payload.putUnsignedInt(opticalflow_sw_version);
              
        packet.payload.putUnsignedInt(sonar_sw_version);
              
        packet.payload.putUnsignedInt(battery_sw_version);
              
        packet.payload.putUnsignedInt(autopilot_hw_version);
              
        
        for (int i = 0; i < product_id.length; i++) {
            packet.payload.putUnsignedByte(product_id[i]);
        }
                    
              
        
        for (int i = 0; i < autopilot_uid.length; i++) {
            packet.payload.putUnsignedByte(autopilot_uid[i]);
        }
                    
        
        return packet;
    }

    /**
    * Decode a autopilot_version message into this class fields
    *
    * @param payload The message to decode
    */
    public void unpack(MAVLinkPayload payload) {
        payload.resetIndex();
              
        this.autopilot_sw_version = payload.getUnsignedInt();
              
        this.opticalflow_sw_version = payload.getUnsignedInt();
              
        this.sonar_sw_version = payload.getUnsignedInt();
              
        this.battery_sw_version = payload.getUnsignedInt();
              
        this.autopilot_hw_version = payload.getUnsignedInt();
              
         
        for (int i = 0; i < this.product_id.length; i++) {
            this.product_id[i] = payload.getUnsignedByte();
        }
                
              
         
        for (int i = 0; i < this.autopilot_uid.length; i++) {
            this.autopilot_uid[i] = payload.getUnsignedByte();
        }
                
        
    }

    /**
    * Constructor for a new message, just initializes the msgid
    */
    public msg_autopilot_version(){
        msgid = MAVLINK_MSG_ID_AUTOPILOT_VERSION;
    }

    /**
    * Constructor for a new message, initializes the message with the payload
    * from a mavlink packet
    *
    */
    public msg_autopilot_version(MAVLinkPacket mavLinkPacket){
        this.sysid = mavLinkPacket.sysid;
        this.compid = mavLinkPacket.compid;
        this.msgid = MAVLINK_MSG_ID_AUTOPILOT_VERSION;
        unpack(mavLinkPacket.payload);        
    }

                  
    /**
    * Returns a string with the MSG name and data
    */
    public String toString(){
        return "MAVLINK_MSG_ID_AUTOPILOT_VERSION -"+" autopilot_sw_version:"+autopilot_sw_version+" opticalflow_sw_version:"+opticalflow_sw_version+" sonar_sw_version:"+sonar_sw_version+" battery_sw_version:"+battery_sw_version+" autopilot_hw_version:"+autopilot_hw_version+" product_id:"+product_id+" autopilot_uid:"+autopilot_uid+"";
    }
}
        