/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * java mavlink generator tool. It should not be modified by hand.
 */

// MESSAGE FORMATION_DANCE PACKING
package com.MAVLink.common;
import com.MAVLink.MAVLinkPacket;
import com.MAVLink.Messages.MAVLinkMessage;
import com.MAVLink.Messages.MAVLinkPayload;

/**
* The formation mission information of dance.
*/
public class msg_formation_dance extends MAVLinkMessage{

    public static final int MAVLINK_MSG_ID_FORMATION_DANCE = 177;
    public static final int MAVLINK_MSG_LENGTH = 254;
    private static final long serialVersionUID = MAVLINK_MSG_ID_FORMATION_DANCE;


      
    /**
    * The formation dance number. E.g: 36.
    */
    public long dance_id;
      
    /**
    * Dance data.
    */
    public short dance_data[] = new short[250];
    

    /**
    * Generates the payload for a mavlink message for a message of this type
    * @return
    */
    public MAVLinkPacket pack(){
        MAVLinkPacket packet = new MAVLinkPacket(MAVLINK_MSG_LENGTH);
        packet.sysid = 255;
        packet.compid = 190;
        packet.msgid = MAVLINK_MSG_ID_FORMATION_DANCE;
              
        packet.payload.putUnsignedInt(dance_id);
              
        
        for (int i = 0; i < dance_data.length; i++) {
            packet.payload.putUnsignedByte(dance_data[i]);
        }
                    
        
        return packet;
    }

    /**
    * Decode a formation_dance message into this class fields
    *
    * @param payload The message to decode
    */
    public void unpack(MAVLinkPayload payload) {
        payload.resetIndex();
              
        this.dance_id = payload.getUnsignedInt();
              
         
        for (int i = 0; i < this.dance_data.length; i++) {
            this.dance_data[i] = payload.getUnsignedByte();
        }
                
        
    }

    /**
    * Constructor for a new message, just initializes the msgid
    */
    public msg_formation_dance(){
        msgid = MAVLINK_MSG_ID_FORMATION_DANCE;
    }

    /**
    * Constructor for a new message, initializes the message with the payload
    * from a mavlink packet
    *
    */
    public msg_formation_dance(MAVLinkPacket mavLinkPacket){
        this.sysid = mavLinkPacket.sysid;
        this.compid = mavLinkPacket.compid;
        this.msgid = MAVLINK_MSG_ID_FORMATION_DANCE;
        unpack(mavLinkPacket.payload);        
    }

        
    /**
    * Returns a string with the MSG name and data
    */
    public String toString(){
        return "MAVLINK_MSG_ID_FORMATION_DANCE - sysid:"+sysid+" compid:"+compid+" dance_id:"+dance_id+" dance_data:"+dance_data+"";
    }
}
        