/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * java mavlink generator tool. It should not be modified by hand.
 */

// MESSAGE FORMATION_REQUEST_INFO PACKING
package com.MAVLink.common;
import com.MAVLink.MAVLinkPacket;
import com.MAVLink.Messages.MAVLinkMessage;
import com.MAVLink.Messages.MAVLinkPayload;

/**
* The formation mission request information.
*/
public class msg_formation_request_info extends MAVLinkMessage{

    public static final int MAVLINK_MSG_ID_FORMATION_REQUEST_INFO = 173;
    public static final int MAVLINK_MSG_LENGTH = 5;
    private static final long serialVersionUID = MAVLINK_MSG_ID_FORMATION_REQUEST_INFO;


      
    /**
    * The formation dance number. E.g: 36.
    */
    public long dance_id;
      
    /**
    * Request of target info. E.g: 1, Request heads info; 2, Request dance info.
    */
    public short target_info;
    

    /**
    * Generates the payload for a mavlink message for a message of this type
    * @return
    */
    public MAVLinkPacket pack(){
        MAVLinkPacket packet = new MAVLinkPacket(MAVLINK_MSG_LENGTH);
        packet.sysid = 255;
        packet.compid = 190;
        packet.msgid = MAVLINK_MSG_ID_FORMATION_REQUEST_INFO;
        packet.payload.putUnsignedByte(target_info);
        packet.payload.putUnsignedInt(dance_id);


        
        return packet;
    }

    /**
    * Decode a formation_request_info message into this class fields
    *
    * @param payload The message to decode
    */
    public void unpack(MAVLinkPayload payload) {
        payload.resetIndex();
        this.target_info = payload.getUnsignedByte();
        this.dance_id = payload.getUnsignedInt();
              

        
    }

    /**
    * Constructor for a new message, just initializes the msgid
    */
    public msg_formation_request_info(){
        msgid = MAVLINK_MSG_ID_FORMATION_REQUEST_INFO;
    }

    /**
    * Constructor for a new message, initializes the message with the payload
    * from a mavlink packet
    *
    */
    public msg_formation_request_info(MAVLinkPacket mavLinkPacket){
        this.sysid = mavLinkPacket.sysid;
        this.compid = mavLinkPacket.compid;
        this.msgid = MAVLINK_MSG_ID_FORMATION_REQUEST_INFO;
        unpack(mavLinkPacket.payload);        
    }

        
    /**
    * Returns a string with the MSG name and data
    */
    public String toString(){
        return "MAVLINK_MSG_ID_FORMATION_REQUEST_INFO - sysid:"+sysid+" compid:"+compid+" dance_id:"+dance_id+" target_info:"+target_info+"";
    }
}
        