/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * java mavlink generator tool. It should not be modified by hand.
 */

// MESSAGE FIRMWARE_DATAS PACKING
package com.MAVLink.common;
import com.MAVLink.MAVLinkPacket;
import com.MAVLink.Messages.MAVLinkMessage;
import com.MAVLink.Messages.MAVLinkPayload;

/**
* The firmware datas.
*/
public class msg_firmware_datas extends MAVLinkMessage {

    public static final int MAVLINK_MSG_ID_FIRMWARE_DATAS = 185;
    public static final int MAVLINK_MSG_LENGTH = 252;
    private static final long serialVersionUID = MAVLINK_MSG_ID_FIRMWARE_DATAS;


      
    /**
    * The id of firmware. E.g: 36.
    */
    public long id;
      
    /**
    * The data of firmware.
    */
    public short data[] = new short[248];
    

    /**
    * Generates the payload for a mavlink message for a message of this type
    * @return
    */
    public MAVLinkPacket pack(){
        MAVLinkPacket packet = new MAVLinkPacket(MAVLINK_MSG_LENGTH);
        packet.sysid = 255;
        packet.compid = 190;
        packet.msgid = MAVLINK_MSG_ID_FIRMWARE_DATAS;
              
        packet.payload.putUnsignedInt(id);
              
        
        for (int i = 0; i < data.length; i++) {
            packet.payload.putUnsignedByte(data[i]);
        }
                    
        
        return packet;
    }

    /**
    * Decode a firmware_datas message into this class fields
    *
    * @param payload The message to decode
    */
    public void unpack(MAVLinkPayload payload) {
        payload.resetIndex();
              
        this.id = payload.getUnsignedInt();
              
         
        for (int i = 0; i < this.data.length; i++) {
            this.data[i] = payload.getUnsignedByte();
        }
                
        
    }

    /**
    * Constructor for a new message, just initializes the msgid
    */
    public msg_firmware_datas(){
        msgid = MAVLINK_MSG_ID_FIRMWARE_DATAS;
    }

    /**
    * Constructor for a new message, initializes the message with the payload
    * from a mavlink packet
    *
    */
    public msg_firmware_datas(MAVLinkPacket mavLinkPacket){
        this.sysid = mavLinkPacket.sysid;
        this.compid = mavLinkPacket.compid;
        this.msgid = MAVLINK_MSG_ID_FIRMWARE_DATAS;
        unpack(mavLinkPacket.payload);        
    }

        
    /**
    * Returns a string with the MSG name and data
    */
    public String toString(){
        return "MAVLINK_MSG_ID_FIRMWARE_DATAS - sysid:"+sysid+" compid:"+compid+" id:"+id+" data:"+data+"";
    }
}
        